Add 'openid' scope to gcloud command
When I run with the `gcloud auth` command as shown, I get this error:

```
ERROR: gcloud crashed (Warning): Scope has changed from "https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/accounts.reauth" to "https://www.googleapis.com/auth/accounts.reauth https://www.googleapis.com/auth/cloud-platform openid https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/userinfo.email".
```

This error message shows that the `openid` scope needs to be added.  After adding this scope, the error message goes away.

See https://github.com/fishtown-analytics/dbt/issues/3040 for more context.