Update bigquery-profile.md
Adding https://www.googleapis.com/auth/iam.test scope to gcloud auth application-default login to get rid of the following error
```shell
These credentials will be used by any library that requests Application Default Credentials (ADC).
/Users/sova/google-cloud-sdk/lib/third_party/google/auth/_default.py:69: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. We recommend you rerun `gcloud auth application-default login` and make sure a quota project is added. Or you can use service accounts instead. For more information about service accounts, see https://cloud.google.com/docs/authentication/
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)
ERROR: (gcloud.auth.application-default.login) User [*********] does not have permission to access projects instance [********:testIamPermissions] (or it may not exist): Request had insufficient authentication scopes
```