[fix] missing indentation level in profile example
Current example copy/paste as is causes the following exception :

```bash
12:32:47  Encountered an error:
argument of type 'NoneType' is not iterable
12:32:47  Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 136, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 206, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/lib/python3.10/site-packages/dbt/main.py", line 233, in run_from_args
    task = parsed.cls.from_args(args=parsed)
  File "/usr/local/lib/python3.10/site-packages/dbt/task/base.py", line 163, in from_args
    return super().from_args(args)
  File "/usr/local/lib/python3.10/site-packages/dbt/task/base.py", line 98, in from_args
    config = cls.ConfigType.from_args(args)
  File "/usr/local/lib/python3.10/site-packages/dbt/config/runtime.py", line 263, in from_args
    project, profile = cls.collect_parts(args)
  File "/usr/local/lib/python3.10/site-packages/dbt/config/runtime.py", line 207, in collect_parts
    profile = cls.collect_profile(args=args)
  File "/usr/local/lib/python3.10/site-packages/dbt/config/runtime.py", line 229, in collect_profile
    profile = cls._get_rendered_profile(args, profile_renderer, profile_name)
  File "/usr/local/lib/python3.10/site-packages/dbt/config/runtime.py", line 200, in _get_rendered_profile
    return Profile.render_from_args(args, profile_renderer, profile_name)
  File "/usr/local/lib/python3.10/site-packages/dbt/config/profile.py", line 428, in render_from_args
    return cls.from_raw_profiles(
  File "/usr/local/lib/python3.10/site-packages/dbt/config/profile.py", line 394, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "/usr/local/lib/python3.10/site-packages/dbt/config/profile.py", line 338, in from_raw_profile_info
    target_name, profile_data = cls.render_profile(
  File "/usr/local/lib/python3.10/site-packages/dbt/config/profile.py", line 298, in render_profile
    raw_profile_data = cls._get_profile_data(raw_profile, profile_name, target_name)
  File "/usr/local/lib/python3.10/site-packages/dbt/config/profile.py", line 215, in _get_profile_data
    if target_name not in outputs:
TypeError: argument of type 'NoneType' is not iterable
```